name: Release
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.16
          otp-version: 26.2
      - name: Fetch dependencies
        run: mix deps.get
      - name: Publish package
        run: mix hex.publish --replace --yes
